In [16]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
os.listdir('/home/BraTS23_dataset')

['testing_data',
 'list',
 'BraTS2023_2017_GLI_Mapping.xlsx',
 'ASNR-MICCAI-BraTS2023-GLI-Challenge-TrainingData.zip',
 'ASNR-MICCAI-BraTS2023-GLI-Challenge-ValidationData.zip',
 '.ipynb_checkpoints',
 'training_data',
 'validation_data']

In [35]:
train_list=[]
path='/home/BraTS23_dataset/BraTS23_dataset/training_data/'
for i in list(os.listdir(path)):
    if i!='.ipynb_checkpoints':
        train_list.append('BraTS23_dataset/training_data/'+i)
train_list=pd.DataFrame(train_list)

In [36]:
train_list

                                                      0
0     BraTS23_dataset/training_data/BraTS-GLI-01511-000
1     BraTS23_dataset/training_data/BraTS-GLI-00341-000
2     BraTS23_dataset/training_data/BraTS-GLI-00072-001
3     BraTS23_dataset/training_data/BraTS-GLI-00090-000
4     BraTS23_dataset/training_data/BraTS-GLI-01332-000
...                                                 ...
996   BraTS23_dataset/training_data/BraTS-GLI-00704-000
997   BraTS23_dataset/training_data/BraTS-GLI-01211-000
998   BraTS23_dataset/training_data/BraTS-GLI-00780-000
999   BraTS23_dataset/training_data/BraTS-GLI-00830-000
1000  BraTS23_dataset/training_data/BraTS-GLI-00767-001

[1001 rows x 1 columns]

In [37]:
# train
train_list=[]
path='/home/BraTS23_dataset/BraTS23_dataset/training_data/'
for i in list(os.listdir(path)):
     if i!='.ipynb_checkpoints':
        train_list.append('BraTS23_dataset/training_data/'+i)
train_list=pd.DataFrame(train_list)
train_list,val_list=train_test_split(train_list,test_size=0.1)
train_list.to_csv('/home/BraTS23_dataset/BraTS23_dataset/list/train_list.txt', header=None, index=None, sep='\t', mode='a')
val_list.to_csv('/home/BraTS23_dataset/BraTS23_dataset/list/val_list.txt', header=None, index=None, sep='\t', mode='a')

In [40]:
val_list

                                                     0
234  BraTS23_dataset/training_data/BraTS-GLI-01432-000
300  BraTS23_dataset/training_data/BraTS-GLI-00596-000
807  BraTS23_dataset/training_data/BraTS-GLI-00025-000
402  BraTS23_dataset/training_data/BraTS-GLI-00818-000
329  BraTS23_dataset/training_data/BraTS-GLI-01476-000
..                                                 ...
977  BraTS23_dataset/training_data/BraTS-GLI-01375-000
214  BraTS23_dataset/training_data/BraTS-GLI-00321-000
469  BraTS23_dataset/training_data/BraTS-GLI-01123-000
313  BraTS23_dataset/training_data/BraTS-GLI-01217-000
0    BraTS23_dataset/training_data/BraTS-GLI-01511-000

[101 rows x 1 columns]

In [27]:
train_list=[]
path='/home/BraTS23_dataset/testing_data/'
for i in list(os.listdir(path)):
    train_list.append('testing_data/'+i)
train_list=pd.DataFrame(train_list)
#train_list,val_list=train_test_split(train_list,test_size=0.1)
train_list.to_csv('/home/BraTS23_dataset/list/testing_list.txt', header=None, index=None, sep='\t', mode='a')
#val_list.to_csv('/home/BraTS23_dataset/list/val_list.txt', header=None, index=None, sep='\t', mode='a')

In [ ]:
# train
train_list=[]
path='/home/MICCAI_BraTS2020_kanglin/brats_2020/MICCAI_BraTS2020_val_split/'
for i in list(os.listdir(path)):
    train_list.append('brats_2020/MICCAI_BraTS2020_val_split/'+i)
train_list=pd.DataFrame(train_list)
train_list.to_csv('/home/MICCAI_BraTS2020_kanglin/val_list.txt', header=None, index=None, sep='\t', mode='a')

In [ ]:
/home/testing_dataset/testing_data/pre_operative_kanglin_1/

In [7]:
train_list=[]
path='/home/testing_dataset/patients_paper_follow_up/MH_dataset_for_60_days/test_data_2/testing_data'
for i in list(os.listdir(path)):
    
    train_list.append('testing_data/'+i)
#train_list=[j for j in train_list if 'BraTS20' in j]
train_list=pd.DataFrame(train_list)
#train_list.to_csv('/home/testing_dataset/patients_paper_follow_up/MH_dataset_for_60_days/test_data_2/list/test.txt', header=None, index=None, sep='\t', mode='a')

In [8]:
train_list

                          0
0     testing_data/35256564
1     testing_data/47303976
2     testing_data/41245644
3     testing_data/40552846
4            testing_data/M
5            testing_data/L
6     testing_data/34114852
7     testing_data/61051121
8            testing_data/Q
9     testing_data/39621144
10           testing_data/O
11    testing_data/46674661
12           testing_data/U
13    testing_data/39991662
14    testing_data/46140963
15    testing_data/47136867
16    testing_data/34290186
17  testing_data/35069039.2
18           testing_data/N
19  testing_data/85435283.2
20           testing_data/X
21           testing_data/J
22    testing_data/36477034
23    testing_data/39597056
24    testing_data/35520522
25    testing_data/47315835
26           testing_data/S
27    testing_data/46351381
28    testing_data/47324599
29    testing_data/41263165
30    testing_data/36104836
31    testing_data/40481407
32    testing_data/45947450
33    testing_data/38216722
34           testing_data/K
35           testing_data/W
36           testing_data/V
37           testing_data/T
38    testing_data/40486118
39    testing_data/41336169
40           testing_data/P
41    testing_data/46292941
42           testing_data/Z
43    testing_data/34259182
44    testing_data/34169940
45    testing_data/45533978
46    testing_data/46481193

In [13]:
train_list

['testing_data/testing_data',
 'testing_data/list',
 'testing_data/.ipynb_checkpoints']